name: detr
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - astunparse=1.6.3=py_0
  - blas=1.0=openblas
  - brotli=1.0.9=h998d150_7
  - brotli-bin=1.0.9=h998d150_7
  - brotli-python=1.0.9=py38h419075a_7
  - bzip2=1.0.8=hf897c2e_4
  - c-ares=1.19.1=h998d150_0
  - ca-certificates=2023.11.17=hcefe29a_0
  - cairo=1.16.0=h537eab0_5
  - cffi=1.16.0=py38h998d150_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py38hb8fdbf2_0
  - cryptography=41.0.7=py38h5077475_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h647bc0d_1
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=h821dc26_0
  - eigen=3.4.0=hd62202e_0
  - expat=2.5.0=h419075a_0
  - expecttest=0.1.3=pyhd3eb1b0_0
  - ffmpeg=4.2.2=hdfaaa67_0
  - fontconfig=2.14.1=h652894d_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h6df46f4_0
  - future=0.18.3=py38hd43f75c_0
  - giflib=5.2.1=h998d150_3
  - glib=2.69.1=h94b7715_2
  - gmp=6.2.1=h22f4aa5_3
  - gnutls=3.6.15=hc6589d6_0
  - graphite2=1.3.14=h22f4aa5_1
  - gst-plugins-base=1.14.1=h419075a_1
  - gstreamer=1.14.1=h998d150_1
  - h5py=3.9.0=py38hebca826_0
  - harfbuzz=4.3.0=hfddee83_1
  - hdf5=1.12.1=h2117f30_3
  - icu=68.2=h3621d8e_0
  - idna=3.4=py38hd43f75c_0
  - importlib_resources=6.1.0=py38hd43f75c_0
  - jpeg=9e=h998d150_1
  - kiwisolver=1.4.4=py38h419075a_0
  - krb5=1.20.1=h2e2fba8_1
  - lame=3.100=hf897c2e_1001
  - lcms2=2.12=h5246980_0
  - ld_impl_linux-aarch64=2.38=h8131f2d_1
  - lerc=3.0=h22f4aa5_0
  - libbrotlicommon=1.0.9=h998d150_7
  - libbrotlidec=1.0.9=h998d150_7
  - libbrotlienc=1.0.9=h998d150_7
  - libclang=14.0.6=default_hd3a980f_1
  - libclang13=14.0.6=default_h5e70c7c_1
  - libcups=2.4.2=hb788212_1
  - libcurl=8.4.0=hfa2bbb0_1
  - libdeflate=1.17=h998d150_1
  - libedit=3.1.20221030=h998d150_0
  - libev=4.33=hfd63f10_1
  - libevent=2.1.12=h6ac735f_1
  - libffi=3.4.4=h419075a_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h6e398d7_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h998d150_0
  - libllvm14=14.0.6=hb8fdbf2_3
  - libnghttp2=1.57.0=hb788212_0
  - libopenblas=0.3.21=hc2e42e2_0
  - libopus=1.3.1=hf897c2e_1
  - libpng=1.6.39=h998d150_0
  - libpq=12.15=h6ac735f_1
  - libssh2=1.10.0=h6ac735f_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h998d150_0
  - libtiff=4.5.1=h419075a_0
  - libunistring=0.9.10=hf897c2e_0
  - libuuid=1.41.5=h998d150_0
  - libvpx=1.8.2=h7c1a80f_0
  - libwebp=1.3.2=he1bfee4_0
  - libwebp-base=1.3.2=h998d150_0
  - libxcb=1.15=h2f4d8fa_0
  - libxkbcommon=1.0.1=h998d150_1
  - libxml2=2.10.4=hd6958ba_0
  - libxslt=1.1.37=h4d22567_0
  - lz4-c=1.9.4=h419075a_0
  - matplotlib=3.7.2=py38hd43f75c_0
  - matplotlib-base=3.7.2=py38hfb1e5ee_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h3140d82_2
  - ncurses=6.4=h419075a_0
  - ndindex=1.7=pyhd8ed1ab_0
  - nettle=3.7.3=h82288b7_1
  - opencv=4.6.0=py38h5f62720_5
  - openh264=1.8.0=h22f4aa5_0
  - openjpeg=2.4.0=hf3eb033_0
  - openssl=3.0.12=h2f4d8fa_0
  - packaging=23.1=py38hd43f75c_0
  - pcre=8.45=h01db608_0
  - pillow=10.0.1=py38h97c669c_0
  - pip=23.3.1=py38hd43f75c_0
  - pixman=0.40.0=h2f4d8fa_1
  - platformdirs=3.10.0=py38hd43f75c_0
  - pooch=1.7.0=py38hd43f75c_0
  - psutil=5.9.0=py38h998d150_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py38hd43f75c_0
  - pyparsing=3.0.9=py38hd43f75c_0
  - pysocks=1.7.1=py38hd43f75c_0
  - python=3.8.18=h4bb2201_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyyaml=6.0.1=py38h998d150_0
  - qt-main=5.15.2=hf18d10e_9
  - qt-webengine=5.15.9=hb462a96_6
  - qtwebkit=5.212=ha4719be_5
  - readline=8.2=h998d150_0
  - requests=2.31.0=py38hd43f75c_0
  - scipy=1.10.1=py38h7caaa05_1
  - setuptools=68.0.0=py38hd43f75c_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h998d150_0
  - tk=8.6.12=h241ca14_0
  - tornado=6.3.3=py38h998d150_0
  - types-dataclasses=0.6.6=pyhd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - urllib3=1.26.18=py38hd43f75c_0
  - versioned-hdf5=1.1=py_0
  - wheel=0.41.2=py38hd43f75c_0
  - x264=1!152.20180806=h2f4d8fa_0
  - xz=5.4.5=h998d150_0
  - yaml=0.2.5=hfd63f10_0
  - zipp=3.11.0=py38hd43f75c_0
  - zlib=1.2.13=h998d150_0
  - zstd=1.5.5=h6a09583_0
  - pip:
    - appdirs==1.4.4
    - asttokens==2.4.1
    - backcall==0.2.0
    - certifi==2023.7.22
    - comm==0.2.0
    - comma-py==1.0.0
    - debugpy==1.8.0
    - decorator==5.1.1
    - executing==2.0.1
    - importlib-metadata==7.0.0
    - ipykernel==6.27.1
    - ipython==8.12.3
    - jedi==0.19.1
    - jupyter-client==8.6.0
    - jupyter-core==5.5.0
    - mako==1.3.0
    - markupsafe==2.1.3
    - matplotlib-inline==0.1.6
    - nest-asyncio==1.5.8
    - numpy==1.24.4
    - parso==0.8.3
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.41
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycuda==2023.1
    - pygments==2.17.2
    - pytools==2023.1.1
    - pyzmq==25.1.2
    - qtconsole==5.5.1
    - qtpy==2.4.1
    - ruamel-yaml==0.18.5
    - ruamel-yaml-clib==0.2.8
    - stack-data==0.6.3
    - tensorrt==8.5.2.2
    - traitlets==5.14.0
    - wcwidth==0.2.12
